version: "3.7"
services:
    ch-node-1:
        container_name: ch-node1
        ports:
            - "8123:8123"
        build:
            context: .
            dockerfile: ch-node1.dockerfile
            args:
                buildno: 1
        volumes:
            - "./ch-node1/ch-data:/var/lib/clickhouse"
        networks:
            ch_lan:
                ipv4_address: 10.92.100.90
                aliases:
                    - ch-node01            
networks:
    ch_lan:
        name: bridge_ch_lan
        driver: bridge 
        ipam:
            config:
              - subnet: 10.92.100.0/24
                #ip_range: 10.92.100.0/24
                #gateway: 10.92.100.1
                #aux_addresses:
                #    host1: 10.92.100.10
                #    host2: 10.92.100.11
                #    host3: 10.92.100.12